modLoader="javafml"
loaderVersion="[32,)"
license="GPL3"

[[mods]]
modId="tac"
version="0.3.10.5"
displayName="Timeless and Classics Guns"
updateJSONURL="https://ClumsyAlien.github.io/TaC_Patch_notes/update.json"
displayURL=""
authors="TaC Squad"
description='''
'''

[[dependencies.tac]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tac]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tac]]
    modId="obfuscate"
    mandatory=true
    versionRange="[0.6.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tac]]
    modId="key_binding_patch"
    mandatory=true
    versionRange="[1.16.5-1.0.2.4,)"
    ordering="NONE"
    side="CLIENT"